app:
  name: "GoVel Config Example"
  debug: true
  version: "1.0.0"
  env: "development"

server:
  host: "localhost" 
  port: 8080
  timeout: "30s"
  ssl:
    enabled: false
    cert_file: ""
    key_file: ""

database:
  host: "localhost"
  port: 5432
  name: "govel_db"
  user: "govel_user"
  password: "secret"
  ssl_mode: "disable"
  max_connections: 100
  timeout: "10s"

cache:
  enabled: true
  driver: "redis"
  host: "localhost"
  port: 6379
  password: ""
  ttl: 3600
  prefix: "govel:"

logging:
  level: "debug"
  format: "json"
  output: 
    - "stdout"
    - "file"
  file_path: "/var/log/govel.log"
  max_size: 100
  max_backups: 3
  max_age: 28

features:
  user_registration: true
  email_verification: false
  social_login:
    - "google"
    - "github"
    - "facebook"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

external_services:
  payment:
    provider: "stripe"
    public_key: "pk_test_..."
    secret_key: "sk_test_..."
  email:
    provider: "sendgrid" 
    api_key: "SG...."
    from_email: "noreply@example.com"
  storage:
    provider: "aws_s3"
    bucket: "my-app-storage"
    region: "us-east-1"